"""
F5_T12 — Calibration Cockpit Dashboard View (Batch 8)
======================================================
Reads the 6 compact JSON files generated by F5_T12 batches and displays
them as interactive Streamlit tables with color-coded decisions.

Panels:
  1) PF Overview — total, directional, managed PF
  2) PF Decomposition Table
  3) No-Progress Compact Table
  4) Managed Exit Damage Table
  5) Filter Contribution Matrix
  6) Symbol Calibration Table
  7) Candidate Promotion Table
"""

import json
import os
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import streamlit as st
import pandas as pd

st.set_page_config(page_title="F5_T12 Calibration Cockpit", layout="wide")
st.title("🎛️ F5_T12 — Calibration Cockpit")
st.caption(
    "Compact calibration tables for deciding KEEP / RESTRICT / RELAX / REMOVE. "
    "Data generated from signal_records and scanner_candidate_shadow_snapshots."
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data")


def load_json(filename: str) -> Optional[Dict[str, Any]]:
    """Load a JSON file from data/ directory."""
    path = os.path.join(DATA_DIR, filename)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError) as e:
        st.error(f"Error loading {filename}: {e}")
        return None


def color_decision(val: Any) -> str:
    """Return a CSS background color for a decision value."""
    if val is None or val == "N/A":
        return ""
    s = str(val).upper()
    if "KEEP" in s or "ALLOW" in s or "PROMOTE" in s or "EXPAND" in s:
        return "background-color: #d4edda; color: #155724"  # green
    if "RESTRICT" in s or "BLOCK" in s or "REMOVE" in s:
        return "background-color: #f8d7da; color: #721c24"  # red
    if "WATCH" in s or "REVIEW" in s or "CONTEXTUAL" in s:
        return "background-color: #fff3cd; color: #856404"  # yellow
    if "INSUFFICIENT" in s or "SAMPLE" in s:
        return "background-color: #e2e3e5; color: #383d41"  # gray
    return ""


def highlight_decision(val: Any) -> str:
    """Return CSS for decision column cells."""
    return color_decision(val)


def fmt(val: Any, decimals: int = 4) -> str:
    """Format a numeric value, returning 'N/A' for None."""
    if val is None or val == "N/A":
        return "N/A"
    try:
        f = float(val)
        if abs(f) >= 10000:
            return f"{f:,.2f}"
        return f"{f:.{decimals}f}"
    except (ValueError, TypeError):
        return str(val)


def fmt_pct(val: Any) -> str:
    """Format as percentage."""
    if val is None:
        return "N/A"
    try:
        return f"{float(val) * 100:.2f}%"
    except (ValueError, TypeError):
        return str(val)


def safe_int(val: Any) -> str:
    """Format as integer or N/A."""
    if val is None:
        return "N/A"
    try:
        return str(int(val))
    except (ValueError, TypeError):
        return str(val)


# ---------------------------------------------------------------------------
# Panel 1: PF Overview
# ---------------------------------------------------------------------------

def render_pf_overview():
    """Render PF Overview metrics from the decomposition table."""
    st.subheader("📊 PF Overview")
    
    data = load_json("01_pf_decomposition_compact.json")
    if data is None:
        st.warning("PF decomposition data not found. Run Batch 2 first.")
        return
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No PF decomposition data available.")
        return
    
    # Find ALL, directional, managed rows
    all_row = next((r for r in rows if r.get("dimension") == "ALL" and r.get("segment") == "ALL"), None)
    dir_row = next((r for r in rows if r.get("dimension") == "exit_family" and r.get("segment") == "directional"), None)
    mgd_row = next((r for r in rows if r.get("dimension") == "exit_family" and r.get("segment") == "managed"), None)
    
    meta = data.get("meta", {})
    col1, col2, col3, col4, col5 = st.columns(5)
    
    with col1:
        st.metric("Total Signals", meta.get("total_signal_records", "?"))
    
    with col2:
        if all_row:
            pf = all_row.get("profit_factor")
            st.metric("PF Total", fmt(pf, 4) if pf is not None else "∞ (no losses)")
        else:
            st.metric("PF Total", "N/A")
    
    with col3:
        if dir_row:
            pf = dir_row.get("profit_factor")
            st.metric("PF Directional", fmt(pf, 4) if pf is not None else "∞ (no losses)")
        else:
            st.metric("PF Directional", "N/A")
    
    with col4:
        if mgd_row:
            pf = mgd_row.get("profit_factor")
            st.metric("PF Managed", fmt(pf, 4) if pf is not None else "∞ (no losses)")
        else:
            st.metric("PF Managed", "N/A")
    
    with col5:
        if all_row:
            net_r = all_row.get("net_r")
            st.metric("Net R Total", fmt(net_r, 2) if net_r is not None else "N/A")
        else:
            st.metric("Net R Total", "N/A")
    
    # Quick summary
    if all_row:
        st.caption(
            f"Wins: {all_row.get('wins', '?')} | Losses: {all_row.get('losses', '?')} | "
            f"Gross Win R: {fmt(all_row.get('gross_win_r'))} | "
            f"Gross Loss R: {fmt(all_row.get('gross_loss_abs_r'))} | "
            f"Decision: **{all_row.get('decision', '?')}**"
        )


# ---------------------------------------------------------------------------
# Panel 2: PF Decomposition Table
# ---------------------------------------------------------------------------

def render_pf_decomposition():
    """Render the PF Decomposition table."""
    st.subheader("📋 PF Decomposition")
    st.caption("Profit Factor broken down by dimension and segment.")
    
    data = load_json("01_pf_decomposition_compact.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No data.")
        return
    
    df = pd.DataFrame(rows)
    
    # Select and order columns
    cols = ["dimension", "segment", "count", "r_values_count", "wins", "losses",
            "gross_win_r", "gross_loss_abs_r", "net_r", "avg_r",
            "avg_win_r", "avg_loss_r", "profit_factor", "decision"]
    display_cols = [c for c in cols if c in df.columns]
    
    df_display = df[display_cols].copy()
    
    # Format numeric columns
    for c in ["gross_win_r", "gross_loss_abs_r", "net_r", "avg_r", "avg_win_r", "avg_loss_r", "profit_factor"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(fmt)
    
    # Color decision column
    styled = df_display.style.apply(highlight_decision, subset=["decision"] if "decision" in df_display.columns else [])
    
    st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))
    
    # Summary stats
    decisions = df["decision"].value_counts().to_dict() if "decision" in df.columns else {}
    if decisions:
        st.caption(f"Decisions: {', '.join(f'**{k}**: {v}' for k, v in decisions.items())}")


# ---------------------------------------------------------------------------
# Panel 3: No-Progress Compact Table
# ---------------------------------------------------------------------------

def render_no_progress():
    """Render the No-Progress Compact table."""
    st.subheader("⏳ No-Progress Compact Optimizer")
    st.caption("Diagnoses root causes of signals that don't advance.")
    
    data = load_json("02_no_progress_compact.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    meta = data.get("meta", {})
    col1, col2, col3 = st.columns(3)
    col1.metric("No-Progress Count", meta.get("no_progress_count", "?"))
    col2.metric("Total with Exit Reason", meta.get("sent_to_telegram_count", "?"))
    col3.metric("No-Progress Rate", fmt_pct(meta.get("no_progress_rate")))
    
    segments = data.get("segments", [])
    if not segments:
        st.info("No segments with sufficient data.")
    else:
        df = pd.DataFrame(segments)
        
        cols = ["segment_type", "segment", "count", "rate_over_sent", "avg_net_r",
                "gross_loss_abs_r", "avg_mfe_r", "avg_mae_r",
                "mfe_zero_count", "mfe_lt_0_15r_count",
                "low_vol_count", "btc_conflict_count", "spread_sensitive_count",
                "action"]
        display_cols = [c for c in cols if c in df.columns]
        
        df_display = df[display_cols].copy()
        
        for c in ["avg_net_r", "gross_loss_abs_r", "avg_mfe_r", "avg_mae_r"]:
            if c in df_display.columns:
                df_display[c] = df_display[c].apply(fmt)
        
        if "rate_over_sent" in df_display.columns:
            df_display["rate_over_sent"] = df_display["rate_over_sent"].apply(fmt_pct)
        
        styled = df_display.style.map(highlight_decision, subset=["action"] if "action" in df_display.columns else [])
        
        st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))
    
    # Top examples
    examples = data.get("top_examples", [])
    if examples:
        with st.expander(f"🔍 Top {len(examples)} No-Progress Examples"):
            df_ex = pd.DataFrame(examples)
            st.dataframe(df_ex, use_container_width=True)


# ---------------------------------------------------------------------------
# Panel 4: Managed Exit Damage Table
# ---------------------------------------------------------------------------

def render_managed_exit_damage():
    """Render the Managed Exit Damage table."""
    st.subheader("🚪 Managed Exit Damage Table")
    st.caption("Measures damage/value of BE/time/no-progress/mfe-stall exits.")
    
    data = load_json("05_managed_exit_damage_table.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    meta = data.get("meta", {})
    col1, col2, col3 = st.columns(3)
    col1.metric("Managed Exits", meta.get("managed_exit_count", "?"))
    col2.metric("Directional", meta.get("directional_count", "?"))
    col3.metric("Managed/Direct Ratio", fmt(meta.get("managed_direct_ratio"), 2))
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No managed exit data.")
        return
    
    df = pd.DataFrame(rows)
    
    cols = ["exit_family", "context", "count", "r_values_count", "avg_r", "net_r",
            "gross_win_r", "gross_loss_abs_r", "profit_factor",
            "avg_mfe_before_exit", "avg_mae_before_exit",
            "avg_duration_min", "managed_direct_ratio", "decision"]
    display_cols = [c for c in cols if c in df.columns]
    
    df_display = df[display_cols].copy()
    
    for c in ["avg_r", "net_r", "gross_win_r", "gross_loss_abs_r", "profit_factor",
              "avg_mfe_before_exit", "avg_mae_before_exit", "avg_duration_min", "managed_direct_ratio"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(fmt)
    
    styled = df_display.style.map(highlight_decision, subset=["decision"] if "decision" in df_display.columns else [])
    
    st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))


# ---------------------------------------------------------------------------
# Panel 5: Filter Contribution Matrix
# ---------------------------------------------------------------------------

def render_filter_contribution():
    """Render the Filter Contribution Matrix."""
    st.subheader("🔍 Filter Contribution Matrix")
    st.caption("Measures which filters avoid losses vs miss winners.")
    
    data = load_json("03_filter_contribution_matrix.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    meta = data.get("meta", {})
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Candidates", meta.get("total_candidates", "?"))
    col2.metric("Unique Reasons", meta.get("unique_reasons", "?"))
    col3.metric("Total Signals", meta.get("total_signal_records", "?"))
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No filter data.")
        return
    
    df = pd.DataFrame(rows)
    
    cols = ["filter_or_reason", "blocked_count", "evaluable_count", "evaluable_rate",
            "hypothetical_wins", "hypothetical_losses", "time_stop_count",
            "avoided_loss_r", "missed_win_r", "net_filter_value_r",
            "profit_factor_if_allowed", "decision"]
    display_cols = [c for c in cols if c in df.columns]
    
    df_display = df[display_cols].copy()
    
    for c in ["avoided_loss_r", "missed_win_r", "net_filter_value_r", "profit_factor_if_allowed"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(fmt)
    
    if "evaluable_rate" in df_display.columns:
        df_display["evaluable_rate"] = df_display["evaluable_rate"].apply(fmt_pct)
    
    styled = df_display.style.map(highlight_decision, subset=["decision"] if "decision" in df_display.columns else [])
    
    st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))
    
    decisions = df["decision"].value_counts().to_dict() if "decision" in df.columns else {}
    if decisions:
        st.caption(f"Decisions: {', '.join(f'**{k}**: {v}' for k, v in decisions.items())}")


# ---------------------------------------------------------------------------
# Panel 6: Symbol Calibration Table
# ---------------------------------------------------------------------------

def render_symbol_calibration():
    """Render the Symbol Calibration table."""
    st.subheader("💱 Symbol Calibration Table")
    st.caption("Symbols classified by real performance, not intuition.")
    
    data = load_json("04_symbol_calibration_table.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    meta = data.get("meta", {})
    col1, col2 = st.columns(2)
    col1.metric("Unique Symbols", meta.get("unique_symbols", "?"))
    col2.metric("Total Signals", meta.get("total_signal_records", "?"))
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No symbol data.")
        return
    
    df = pd.DataFrame(rows)
    
    cols = ["symbol", "count", "directional_count", "managed_count",
            "tp_count", "sl_count", "no_progress_count",
            "gross_win_r", "gross_loss_abs_r", "net_r",
            "profit_factor", "avg_mfe_r", "avg_mae_r",
            "weekday_pf", "weekend_pf", "managed_direct_ratio", "decision"]
    display_cols = [c for c in cols if c in df.columns]
    
    df_display = df[display_cols].copy()
    
    for c in ["gross_win_r", "gross_loss_abs_r", "net_r", "profit_factor",
              "avg_mfe_r", "avg_mae_r", "weekday_pf", "weekend_pf", "managed_direct_ratio"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(fmt)
    
    styled = df_display.style.map(highlight_decision, subset=["decision"] if "decision" in df_display.columns else [])
    
    st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))
    
    decisions = df["decision"].value_counts().to_dict() if "decision" in df.columns else {}
    if decisions:
        st.caption(f"Decisions: {', '.join(f'**{k}**: {v}' for k, v in decisions.items())}")


# ---------------------------------------------------------------------------
# Panel 7: Candidate Promotion Table
# ---------------------------------------------------------------------------

def render_candidate_promotion():
    """Render the Candidate Promotion table."""
    st.subheader("🏆 Candidate Promotion Table")
    st.caption("Which OFA patterns deserve promotion or restriction.")
    
    data = load_json("06_candidate_promotion_table.json")
    if data is None:
        st.warning("Data not found.")
        return
    
    meta = data.get("meta", {})
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Candidates", meta.get("total_candidates", "?"))
    col2.metric("Evaluable", meta.get("evaluable_candidates", "?"))
    col3.metric("Min Count", meta.get("min_count_per_segment", "?"))
    
    rows = data.get("rows", [])
    if not rows:
        st.info("No candidate promotion data.")
        return
    
    df = pd.DataFrame(rows)
    
    cols = ["candidate_class", "count", "evaluable_count",
            "hypothetical_wins", "hypothetical_losses",
            "hypothetical_pf", "net_r",
            "avg_mfe_r", "avg_mae_r",
            "top_symbols", "promotion_decision", "required_confirmations"]
    display_cols = [c for c in cols if c in df.columns]
    
    df_display = df[display_cols].copy()
    
    for c in ["hypothetical_pf", "net_r", "avg_mfe_r", "avg_mae_r"]:
        if c in df_display.columns:
            df_display[c] = df_display[c].apply(fmt)
    
    styled = df_display.style.map(highlight_decision, subset=["promotion_decision"] if "promotion_decision" in df_display.columns else [])
    
    st.dataframe(styled, use_container_width=True, height=min(400, 35 * len(df_display) + 35))
    
    decisions = df["promotion_decision"].value_counts().to_dict() if "promotion_decision" in df.columns else {}
    if decisions:
        st.caption(f"Decisions: {', '.join(f'**{k}**: {v}' for k, v in decisions.items())}")


# ---------------------------------------------------------------------------
# Main render
# ---------------------------------------------------------------------------

def main():
    # Check if data files exist
    files_exist = all(
        os.path.exists(os.path.join(DATA_DIR, f))
        for f in ["01_pf_decomposition_compact.json", "02_no_progress_compact.json",
                  "03_filter_contribution_matrix.json", "04_symbol_calibration_table.json",
                  "05_managed_exit_damage_table.json", "06_candidate_promotion_table.json"]
    )
    
    if not files_exist:
        st.warning(
            "⚠️ Some F5_T12 data files are missing. "
            "Run the batch generators first:\n\n"
            "```bash\n"
            "python src/f5_t12_generate_pf_decomposition.py\n"
            "python src/f5_t12_generate_no_progress_compact.py\n"
            "python src/f5_t12_generate_managed_exit_damage.py\n"
            "python src/f5_t12_generate_filter_contribution.py\n"
            "python src/f5_t12_generate_symbol_calibration.py\n"
            "python src/f5_t12_generate_candidate_promotion.py\n"
            "```"
        )
        return
    
    # Last generation time
    timestamps = []
    for f in ["01_pf_decomposition_compact.json", "02_no_progress_compact.json",
              "03_filter_contribution_matrix.json", "04_symbol_calibration_table.json",
              "05_managed_exit_damage_table.json", "06_candidate_promotion_table.json"]:
        path = os.path.join(DATA_DIR, f)
        if os.path.exists(path):
            timestamps.append(os.path.getmtime(path))
    if timestamps:
        latest = datetime.fromtimestamp(max(timestamps))
        st.caption(f"🕐 Data last updated: {latest.strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Render panels
    render_pf_overview()
    st.divider()
    
    tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
        "📋 PF Decomposition",
        "⏳ No-Progress",
        "🚪 Managed Exits",
        "🔍 Filter Matrix",
        "💱 Symbols",
        "🏆 Candidates",
    ])
    
    with tab1:
        render_pf_decomposition()
    
    with tab2:
        render_no_progress()
    
    with tab3:
        render_managed_exit_damage()
    
    with tab4:
        render_filter_contribution()
    
    with tab5:
        render_symbol_calibration()
    
    with tab6:
        render_candidate_promotion()
    
    # Footer with batch info
    st.divider()
    st.caption(
        "F5_T12 — Calibration Cockpit | Batches 2-7 generate JSON, Batch 8 renders. "
        "No TP/SL/lifecycle/schema modified. "
        "Killzone replaced by session_bucket + weekend."
    )


if __name__ == "__main__":
    main()
